### ISSUE TITLE
[AUTOGLUON] Early Stopping in TimeSeriesPredictor?

### ISSUE THREAD

**Issue by DAD-FOX** [amazon-science/chronos-forecasting#254] opened 2024-12-27 11:15 UTC
# Clarification on models Using Early Stopping by default in TimeSeriesPredictor

## Description  
I would like to understand which models in the `TimeSeriesPredictor` use early stopping by default. Additionally, could you please clarify how early stopping is implemented and configured in these models?  

### Key Questions  
1. **Default Usage**:  
   - Which models in `TimeSeriesPredictor` (e.g., Temporal Fusion Transformer, DeepAR, etc.) have early stopping activated by default?  

2. **Default Parameters**:  
   - Are there any default configurations for early stopping, such as:  
   - Patience (number of epochs to wait before stopping)?  
   - Minimum delta (the threshold for improvement)?  

4. **Customization**:  
   - How can I customize early stopping for models in `TimeSeriesPredictor`?  

Thank you for your assistance!

**Comment by lostella** [comment] 2024-12-27 11:51
Closing as duplicate of https://github.com/autogluon/autogluon/issues/4757

@DAD-FOX please use AutoGluon’s issue trailer for issues related to AutoGluon specifically, and avoid duplication.

**Closed by lostella** 2024-12-27 11:51 UTC
